### ISSUE TITLE
ASK vs SELECT

### ISSUE THREAD

**Issue by ktk** [Swirrl/data-cube-validations#6]
I just stumbled accross this repository, looks very interesting. I quickly had a look at the queries and if I get that right you basically re-wrote the ASK queries from the RDF Data Cube spec to figure out what is *wrong* in your data, do I get that right? So if I get something back in a query, that's what should be fixed?

**Comment by lkitching** [comment]
Hi, yes it's the intention that the `SELECT` queries return a sequence of items that violate the corresponding constraint. If you run these queries with [`RDF validator`](https://github.com/Swirrl/rdf-validator) the test runner counts any bindings returned from a `SELECT` query as a test failure.

**Comment by ktk** [comment]
Cool tnx!
